# Generated by Django 4.0.4 on 2022-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_book_id_format_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_author', to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(related_name='book_shelf', to='books.bookshelf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(related_name='book_lang', to='books.language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(related_name='book_subject', to='books.subject'),
        ),
    ]
